### ISSUE TITLE
HELP PLEASE

### ISSUE THREAD

**Issue by Thirdy-jea** [Bottelet/Flarepoint-crm#101]
I don't know what I did wrong during the installation process. Did everything that was said in the steps to installation. Please help, thanks

![image](https://user-images.githubusercontent.com/40558801/49713250-e3a52880-fc82-11e8-9b4d-e9eb34e61898.png)

**Comment by mirorauhala** [comment]
You need to change the web root of your server point to the public/ folder which you can see from the screenshot you posted.

**Comment by umefarooq** [comment]
just try http://localhost/flarepoint/public

**Comment by Bottelet** [comment]
@Thirdy-jea , as said, Laravel root should be `public`

**Comment by baradhili** [comment]
Actually I'm getting similar, @Bottelet , my apache conf is pointing to /var/www/flarepoint/public but I get "The requested URL /login was not found on this server." .. looking at routes/web.php I can't see a route for login?..

**Comment by mirorauhala** [comment]
@baradhili https://laravel.com/docs/5.6/#pretty-urls
