### ISSUE TITLE
Invoice causes error

### ISSUE THREAD

**Issue by Thirdy-jea** [Bottelet/Flarepoint-crm#102]
Is there a bug in the program? The invoice doesn't seem to work sir.
![image](https://user-images.githubusercontent.com/40558801/49717294-97adb000-fc91-11e8-86aa-3f14f3d6a2d3.png)

**Comment by Thirdy-jea** [comment]
I clicked the 'See the Invoice' button and then the error occurred. Is there any solution for this sir?

**Comment by Thirdy-jea** [comment]
![image](https://user-images.githubusercontent.com/40558801/49717343-be6be680-fc91-11e8-81b3-777ae2b6c5af.png)

**Comment by Bottelet** [comment]
Seems like it links to the wrong invoice, should be a quick fix, If I remember correctly, it needs to use the `external_id`

**Comment by jhuebel** [comment]
Resolved in develop branch. The URL for that link was malformed. Switched to using route helper instead of manually building URL.
