### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by DevMostafa** [Bottelet/Flarepoint-crm#104]
I have these error after browsing the page for a complete successful installation
http://localhost/flarepoint/public/

Not Found
The requested URL /flarepoint/public/login was not found on this server.
Apache/2.4.29 (Ubuntu) Server at localhost Port 80

I've made the following      https://github.com/Bottelet/Flarepoint-crm/wiki/Install          exactly
and I've made the 
sudo chmod -R guo+w storage bootstrap/
php artisan cache:clear

and I have this error into the storage/logs/laravel 
permission denied in /var/www/html/flarepoint/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php

then I have made some steps to cancel re-generating this error and still cannot open the flarepoint

can anyone help me?

**Comment by SkowronekArt** [comment]
I'm having the same issue.
The flarepoint/public is set as the root directory on my localhost. No errors during installation, I use apache2 on Mac.
Has anyone found the solution? Please, please, help!

**Comment by SkowronekArt** [comment]
I got it now! It was `AllowOverride _None_` on my apache server :)

**Comment by jhuebel** [comment]
@DevMostafa, please follow the steps here for pretty URLs:

https://laravel.com/docs/5.8#web-server-configuration

Also, as @SkowronekArt mentioned, you'll need to AllowOverride in your main Apache server settings. On Ubuntu 18.04, you can modify your `/etc/apache2/apache2.conf` file. Make sure your `/var/www` directory settings look similar to this:

```
<Directory /var/www/>
        Options -Indexes FollowSymLinks
        AllowOverride All
        Require all granted
</Directory>
```

The important line is `AllowOverride All`. I also explicitly unset `Indexes`, so you don't accidentally show an index of files somewhere. Then restart Apache and you should be good.

Other Linux distributions may have the main Apache config file located in /etc/httpd or something similar. You'll just have to hunt for it.

**Comment by DevMostafa** [comment]
> @DevMostafa, please follow the steps here for pretty URLs:
> 
> https://laravel.com/docs/5.8#web-server-configuration
> 
> Also, as @SkowronekArt mentioned, you'll need to AllowOverride in your main Apache server settings. On Ubuntu 18.04, you can modify your `/etc/apache2/apache2.conf` file. Make sure your `/var/www` directory settings look similar to this:
> 
> ```
> <Directory /var/www/>
>         Options -Indexes FollowSymLinks
>         AllowOverride All
>         Require all granted
> </Directory>
> ```
> 
> The important line is `AllowOverride All`. I also explicitly unset `Indexes`, so you don't accidentally show an index of files somewhere. Then restart Apache and you should be good.
> 
> Other Linux distributions may have the main Apache config file located in /etc/httpd or something similar. You'll just have to hunt for it.

Thanks @jhuebel
