### ISSUE TITLE
Class App\Http\Controllers\Auth\RegisterController does not exist

### ISSUE THREAD

**Issue by chinmayambardekar** [Bottelet/Flarepoint-crm#107]
Few PHP artisan commands fail saying "Class App\Http\Controllers\Auth\RegisterController does not exist".
The path has no file as RegisterController.php

**Comment by Bottelet** [comment]
@chinmayambardekar It's been fixed now 
https://github.com/Bottelet/Flarepoint-crm/pull/111
by @jhuebel Thanks!
