### ISSUE TITLE
Separate Contacts from Clients

### ISSUE THREAD

**Issue by jhuebel** [Bottelet/Flarepoint-crm#109]
Separate the individual contact information from the company information. At the medium and large business scales, there are often multiple contacts involved. The ability to document all those contacts would be ideal.

**Comment by jhuebel** [comment]
I wanted to open the ticket first, but let you know that I'll be forking Flarepoint to add the functionality myself. I'm not a great Laravel developer, but I get by. Will be happy to pay back the project with a pull request once I'm done with my changes.

**Comment by Bottelet** [comment]
Cool, go for it, I'll gladly review your PR when it's ready

**Comment by jhuebel** [comment]
If you're interested in following along with my progress, here's the branch I'm working on:

https://github.com/jhuebel/Flarepoint-crm/tree/contacts

Overview of the changes so far:

- Migrations done for the schema changes and data migration (in case you're a current user with live data).
- Views affected by renaming the clients.name field to clients.primary_contact_name are updated.
- The dataTable in the All Clients view now sorts by Company Name.
- The Client view is now more company focused, rather than contact focused.
- clients.primary_contact_name is no longer a required field but was left in the client record in case the user doesn't want to create a contact record for a client with only one contact.
- Laid the ground work for adding region/state and country to the client and contact addresses using Doug Sisk's Laravel-Country-State package.

Regarding contact data migration, it's pretty straightforward. In one of the migrations, I create a new contact record for each client using the primary contact name, address, phone numbers and email address. The data in the client record remains unchanged. I suppose this wasn't strictly necessary, since every client currently has only one contact. I guess I could have left that to the user. 🤷‍♂ 

Anyway, I should have the views for the Contacts done in the next day or two. As part of that, I'll probably move validation errors underneath each text field in all the create/update forms (not just for Client and Contact forms), since the forms are so long that the errors aren't visible at the bottom of the page.

**Comment by fr3em1nd** [comment]
hey thanks! this helped me.

**Comment by jhuebel** [comment]
Oof... using repositories makes me want to blow my brains out.

**Comment by jhuebel** [comment]
Finishing up the contacts.show view, then I'll make the validation error changes. At that point, I should be ready to submit the pull request. I think I'm going to save the State and Country field feature addition until after the contacts feature is done.

**Comment by jhuebel** [comment]
@Bottelet, any objections to requiring PHP 7.x? I really prefer to use the null coalescing operator in forms with validation. If you'll look here, you can see how much cleaner this form looks after a refactor with that operator:

https://github.com/jhuebel/Flarepoint-crm/blob/39b8242300df7fc84d87a33b71a7c670c0aa05b2/resources/views/clients/form.blade.php

**Comment by Bottelet** [comment]
@jhuebel I agree repo pattern is a pain, it's a regret I've struggled with myself. Also no, i think its fine with the PHP version, so it is up-to-date

**Comment by jhuebel** [comment]
#110

**Comment by Bottelet** [comment]
#110 has been merged @jhuebel  Thanks!
