### ISSUE TITLE
Request to become a maintainer

### ISSUE THREAD

**Issue by jhuebel** [Bottelet/Flarepoint-crm#115]
Regarding my last comment on #114, it was suggested to me elsewhere that I should request to become a maintainer rather than fork the project entirely. How would you feel about that? Also, keep in mind that I would be making significant and breaking changes in upcoming versions.

**Comment by Bottelet** [comment]
@jhuebel I don't think that would be a problem with that, we would probably have to discuss a few things, could you maybe shoot me an email at cbottelet@gmail.com
