### ISSUE TITLE
Class 'App\Models\permissions' not found

### ISSUE THREAD

**Issue by giesta** [Bottelet/Flarepoint-crm#117]
When I am trying to edit role's permissions as Administrator I am getting this error: "Class 'App\Models\permissions' not found". 
Settings -> Overall Settings -> Save Role
Do you have any suggestions?

**Comment by jhuebel** [comment]
A class name should always start with a capital letter. So the issue here is "permissions". To fix it, In `app/Models/Role.php` change the permissions() method from:

```
public function permissions()
{
    return $this->belongsToMany(permissions::class, 'permission_role', 'role_id', 'permission_id');
}
```

to this:

```
public function permissions()
{
    return $this->belongsToMany(Permissions::class, 'permission_role', 'role_id', 'permission_id');
}

```

Notice the capitalization change of "Permissions::class".
