### ISSUE TITLE
AJAX calls column names

### ISSUE THREAD

**Issue by SkowronekArt** [Bottelet/Flarepoint-crm#118]
I think I found an issue in 
`https://github.com/Bottelet/Flarepoint-crm/blob/master/resources/views/clients/index.blade.php`

Ajax calls the `clients.salesperson` column, while the name of the column is `clients.user_id`

**Comment by SkowronekArt** [comment]
So it is in 
`resources/views/contacts/index.blade.php`
`contacts.client_name` should be `contacts.client_id`

**Comment by jhuebel** [comment]
Are you receiving any errors?

If you look at the `app/Http/Controllers/ClientsController.php` and `app/Http/Controllers/ContactsController.php`, there is an `anyData` method in each. Those generate the column data for the the tables. They send the salesperson's name and the client's name, respectively. They aren't supposed to populate the table with the IDs.

The way those lists work is a little weird.

**Comment by SkowronekArt** [comment]
Yes, I received this error while sorting by client on the contact page:
`DataTables warning: table id=contacts-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7`

**Comment by jhuebel** [comment]
Ah, sorting... That was the missing piece of information I needed. I'll look into it today. Since I'm not super familiar with the DataTables component used for the lists, it may take me a day or two to sort out.

**Comment by jhuebel** [comment]
OK, this is fixed in 1.3.2 which I just pushed out to the master branch.
