### ISSUE TITLE
docker php version conflicts

### ISSUE THREAD

**Issue by slayerbleast** [Bottelet/Flarepoint-crm#119]
I'm trying this project with docker.

But when I did composer install inside docker container gives errors about php version:

 Problem 1
    - Installation request for doctrine/cache v1.8.0 -> satisfiable by doctrine/cache[v1.8.0].
    - doctrine/cache v1.8.0 requires php ~7.1 -> your PHP version (7.0.33) does not satisfy that requirement.
  Problem 2
    - Installation request for doctrine/dbal v2.9.2 -> satisfiable by doctrine/dbal[v2.9.2].
    - doctrine/dbal v2.9.2 requires php ^7.1 -> your PHP version (7.0.33) does not satisfy that requirement.
  Problem 3
    - Installation request for doctrine/event-manager v1.0.0 -> satisfiable by doctrine/event-manager[v1.0.0].
    - doctrine/event-manager v1.0.0 requires php ^7.1 -> your PHP version (7.0.33) does not satisfy that requirement.
  Problem 4
    - Installation request for doctrine/inflector v1.3.0 -> satisfiable by doctrine/inflector[v1.3.0].
    - doctrine/inflector v1.3.0 requires php ^7.1 -> your PHP version (7.0.33) does not satisfy that requirement.
  Problem 5
    - Installation request for symfony/contracts v1.1.0 -> satisfiable by symfony/contracts[v1.1.0].
    - symfony/contracts v1.1.0 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
  Problem 6
    - Installation request for symfony/event-dispatcher v4.2.8 -> satisfiable by symfony/event-dispatcher[v4.2.8].
    - symfony/event-dispatcher v4.2.8 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
  Problem 7
    - Installation request for symfony/translation v4.2.8 -> satisfiable by symfony/translation[v4.2.8].
    - symfony/translation v4.2.8 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
  Problem 8
    - Installation request for doctrine/instantiator 1.2.0 -> satisfiable by doctrine/instantiator[1.2.0].
    - doctrine/instantiator 1.2.0 requires php ^7.1 -> your PHP version (7.0.33) does not satisfy that requirement.
  Problem 9
    - Installation request for myclabs/deep-copy 1.9.1 -> satisfiable by myclabs/deep-copy[1.9.1].
    - myclabs/deep-copy 1.9.1 requires php ^7.1 -> your PHP version (7.0.33) does not satisfy that requirement.
  Problem 10
    - Installation request for symfony/yaml v4.2.8 -> satisfiable by symfony/yaml[v4.2.8].
    - symfony/yaml v4.2.8 requires php ^7.1.3 -> your PHP version (7.0.33) does not satisfy that requirement.
  Problem 11
    - doctrine/inflector v1.3.0 requires php ^7.1 -> your PHP version (7.0.33) does not satisfy that requirement.
    - laravel/framework v5.4.36 requires doctrine/inflector ~1.1 -> satisfiable by doctrine/inflector[v1.3.0].
    - Installation request for laravel/framework v5.4.36 -> satisfiable by laravel/framework[v5.4.36].

Seems is needed php 7.1 at least to run this project, but on docker configuration it uses php:7.0-fpm.

Can we change this? to php7.1 or even 7.2?

Thank you

**Comment by jhuebel** [comment]
You're welcome to try changing the `.docker/flarepoint-php/Dockerfile` to resolve this. You may be able to simply change the first line to:

```
FROM php:7.2-fpm
```

The Docker configuration included with Flarepoint is currently unmaintained. Since I don't use Docker, I didn't have any plans to update it.

That said, I'll add it to the roadmap for 2.0, which will come out sometime after I finish the Laravel 5.8/Bootstrap 4 migration. I can obviously see the benefit of having a working Docker configuration, especially since I'm working on making Flarepoint more enterprise-friendly. In the meantime, I would be happy to accept pull requests that update this sooner.
