### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kannantncbe** [Bottelet/Flarepoint-crm#123]
Hi,

I try to execute this command.
php artisan migrate --seed

I go the following error.

In ProcessUtils.php line 43:

  The Symfony\Component\Process\ProcessUtils::escapeArgument() method is deprecated since Symfony 3.3 and will be removed in 4.0. Use a command line array or give en
  v vars to the Process::start/run() method instead.

**Comment by jhuebel** [comment]
Please reply with the output of the following command:
```
composer show
```
Or if you have an older version of composer, you may have to add the `-i` argument at the end.

**Comment by jhuebel** [comment]
According to issue #21281 on the Laravel repo, this is just a warning. Closing.
