### ISSUE TITLE
Is this app using AdminLTE, or something else?

### ISSUE THREAD

**Issue by ilhamhmdn** [Bottelet/Flarepoint-crm#124]

**Comment by jhuebel** [comment]
This doesn't use AdminLTE. It currently uses vanilla Bootstrap 3 with a custom sidebar component and Chart.js. That will change in Flarepoint CRM 2.0, though. We'll be moving to Bootstrap 4. But using AdminLTE could certainly be an option.

**Comment by jhuebel** [comment]
I take that back. AdminLTE isn't an option, since it's based on Bootstrap 3 (and we're moving to 4). So a different Admin control panel would be necessary.
