### ISSUE TITLE
I can't reset my password

### ISSUE THREAD

**Issue by giesta** [Bottelet/flarepoint-crm#128]
When trying to reset my password I am getting the error "Cannot send message without a sender address"

**Comment by cyborix** [comment]
You have to configure [SMTP](https://stackoverflow.com/questions/31871806/laravel-homestead-swift-cannot-send-message-without-a-sender-address) **.env** **Mail.php**

you can use 
* [Mailtrap.io](https://mailtrap.io/)
*Gmail
this all are free SMTP

**Comment by cyborix** [comment]
You have to configure [SMTP](https://stackoverflow.com/questions/31871806/laravel-homestead-swift-cannot-send-message-without-a-sender-address) **.env** & **Mail.php**

you can use 
* [Mailtrap.io](https://mailtrap.io/)
* Gmail
this all are free SMTP

**Comment by giesta** [comment]
SMTP is configured and I am getting this error.

**Comment by giesta** [comment]
I am using Mailtrap.io
![image](https://user-images.githubusercontent.com/47950470/64640990-e00e2000-d413-11e9-800d-0a9f150a7d51.png)

**Comment by cyborix** [comment]
welcome bro...! 🤟👍
