### ISSUE TITLE
can't get the 5.8 branch to work?

### ISSUE THREAD

**Issue by vesper8** [Bottelet/flarepoint-crm#129]
I just checked out the laravel-5.8 branch, followed the installation instructions and it all went smoothly. I can access the CRM and log in, but then once I'm in the gui seems to not be working. For example when clicking on most of the menu items such as Clients, Tasks, Leads, the sub-menu does not expand and I see this error in my console:

```
Uncaught TypeError: Cannot read property 'querySelectorAll' of null
    at e.n._getParent (app.js:1)
    at new e (app.js:1)
    at HTMLDivElement.<anonymous> (app.js:1)
    at Function.each (app.js:1)
    at M.fn.init.each (app.js:1)
    at M.fn.init.e._jQueryInterface [as collapse] (app.js:1)
    at HTMLDivElement.<anonymous> (app.js:1)
    at Function.each (app.js:1)
    at M.fn.init.each (app.js:1)
    at HTMLAnchorElement.<anonymous> (app.js:1)
```

On top of following the installation instructions, I also ran `yarn` and `yarn prod` thinking that this was needed, but this didn't make this problem go away

Any idea @jhuebel ?

**Comment by jhuebel** [comment]
5.8 branch isn't ready for use. It's currently in a non-functional state.

**Comment by jmichaelterenin** [comment]
Hi there, is there a timeline for when this package might be available for Laravel 5.8?

**Comment by jhuebel** [comment]
I should begin working on this again in the next couple of weeks. I’m
hoping to have the migration complete by the end of December. I apologize
for the delay, but I had to put improvements to Flarepoint on hold since I
recently moved to a new city and job.

**Comment by vesper8** [comment]
well might as well skip ahead to Laravel 6 in that case : ) since this is used as a standalone package, seems to make sense to upgrade to the latest version at the time

**Comment by jhuebel** [comment]
That’s actually the intent. Just haven’t sat down to evaluate which version
to switch to yet. :-)

**Comment by jhuebel** [comment]
Pulled the laravel-5.8 branch for now. I had pushed it out to github so I could work between my home and work computers. It wasn't meant to be public yet.
