### ISSUE TITLE
Laravel 6 

### ISSUE THREAD

**Issue by cyborix** [Bottelet/flarepoint-crm#136]
Im trying to upgrade flarepoint  to laravel 6. everything is working  except role based management  (**Entrust**) [https://github.com/Zizaco/entrust](url)
entrust not supporting for laravel 6 
any alternative solution or other package 
i need help on this  ......!!
please help me guys .....!!

**Comment by 3gen** [comment]
How about spatie’s permission: https://github.com/spatie/laravel-permission


On Mar 19, 2020, at 7:12 AM, gigas <notifications@github.com> wrote:

﻿

Im trying to upgrade flarepoint to laravel 6. everything is working except role based management (Entrust) https://github.com/Zizaco/entrust<url>
entrust not supporting for laravel 6
any alternative solution or other package
i need help on this ......!!
please help me guys .....!!

**Comment by Bottelet** [comment]
I've wanted to fix the entire permissions on Flarepoint for some time as entrust seems to be no longer actively maintained. Spatie could be a solution. There is also a fix out there on how to Entrust working with < Laravel 6, but don't remember it. I'll try and find it later.

**Comment by cyborix** [comment]
@3gen thanks bro i  try that...!
@Bottelet  can share your the FIX please ....!

**Comment by cyborix** [comment]
Anything guys ..... spatie’s not helpful for my case 
@Bottelet any idea ...?

**Comment by Bottelet** [comment]
I found it last time by searching on the entrust repo.
https://github.com/Zizaco/entrust/issues?q=laravel+6
I had it fixed, can't find the exact solution i found last time.

Den man. 23. mar. 2020 kl. 10.34 skrev gigas <notifications@github.com>:
