### ISSUE TITLE
Add RTL support

### ISSUE THREAD

**Issue by YazeedAlsaif** [Bottelet/Flarepoint-crm#17]
Hello

I have been searching for something like this for a long time.

Is there a plan to support RTL languages? I am here to help if you wish with Arabic in design & translation.

Thanks :) :+1:

**Comment by Bottelet** [comment]
Hello @YazeedAlsaif, It was the plan to integrate some translation to the CRM, and I will also look into RTL. I am not 100% sure, when I will get it done, but might be one of the next things I look at

**Comment by Bottelet** [comment]
I am currently working on translations, and will also look into RTL

**Comment by Bottelet** [comment]
@YazeedAlsaif I have to admit, I'm not sure how 100% to add RTL, but it is translatable now, but gonna have to research this a bit, so I'm not gonna put it as a top priority atm.
