### ISSUE TITLE
Can't install due to PDO class not found error

### ISSUE THREAD

**Issue by avoidik** [Bottelet/Flarepoint-crm#20]
**composer install** throws:
```
Fatal error: Class 'PDO' not found in /home/web/web/config/database.php on line 16
```
**php** and **php-cli** provides this info for **print_r(PDO::getAvailableDrivers());**
```
Array ( [0] => sqlite [1] => mysql [2] => pgsql ) 
```
**phpinfo** shows that pdo is enabled.
PHP Version 5.6.16

What's problem here?

**Comment by avoidik** [comment]
This is the shared hosting and i'm using this command.
```
/opt/php/bin/php -c /home/web/etc/php.ini /home/web/composer.phar install
```

**Comment by avoidik** [comment]
I'm sorry. Solved this by myself.
```
export PHPRC=/home/web/etc/php.ini
```
and then just
```
php /home/web/composer.phar install
```

**Comment by Bottelet** [comment]
Perfect @avoidik  :+1: , sorry for the late response
