### ISSUE TITLE
Create user

### ISSUE THREAD

**Issue by MAliRazasaeed** [Bottelet/Flarepoint-crm#24]
When i create new user I give him department but it show exception like.
The departments field is required.
Image attached: 
![capture](https://cloud.githubusercontent.com/assets/21223565/19215238/ec30c12c-8db1-11e6-864e-2a0cdcfbef3c.PNG)

**Comment by Bottelet** [comment]
Thanks for the heads up @MAliRazasaeed It is fixed now https://github.com/Bottelet/Flarepoint-crm/commit/4b7141b56c7e28f46d1059cb92297bc582a002f2, you can just pull down the changes and all should be good!

**Comment by MAliRazasaeed** [comment]
Thanks for your help. you are awesome man.
