### ISSUE TITLE
Error in image selection

### ISSUE THREAD

**Issue by MAliRazasaeed** [Bottelet/Flarepoint-crm#25]
Dear: When i select the image to create New user it give Exception error:

images are attached:
![12345](https://cloud.githubusercontent.com/assets/21223565/19221458/53fd8dac-8e5d-11e6-831f-c0f436b38dfd.PNG)
![1233](https://cloud.githubusercontent.com/assets/21223565/19221459/54f0740e-8e5d-11e6-82dc-250960dde784.PNG)

**Comment by Bottelet** [comment]
Thanks again, for finding an error, I will look into it later, and see if I can get it fixed tonight! or hopefully tomorrow

**Comment by Bottelet** [comment]
Hmm okay, it seems like the entire Image "system" is failing me, I will have to give it a look over the weekend, or if I get some more time throughout the week. Sorry bout it @MAliRazasaeed.

**Comment by Bottelet** [comment]
Fixed https://github.com/Bottelet/Flarepoint-crm/commit/5091b74bedb4c3e0c8dd3268a05c34d6edd8f2c9 :)
