### ISSUE TITLE
Hi, I am getting this error after installation by this url (localhost:8888/crm3/public) this is error(Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /Applications/MAMP/htdocs/crm3/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 475)

### ISSUE THREAD

**Issue by mommand** [Bottelet/Flarepoint-crm#27]

**Comment by Bottelet** [comment]
Hmm this seems very weird, can you explain in steps what you are doing @mommand?

**Comment by punit-gajjar** [comment]
I am getting same issue, Can you please help me out to resolve this ?
Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in F:\wamp\www\punit\Flarepoint_crm\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php on line 477
