### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by cerelli** [Bottelet/Flarepoint-crm#28]
When i try to install
`composer install`
This is the error
Your requirements could not be resolved to an installable set of packages

Why?

Thanks

**Comment by cerelli** [comment]
excuse me, but i can launch a 
`composer create-project .....` after ???

**Comment by cerelli** [comment]
`[marco@marco-note flarepoint]$ composer install
Failed loading /usr/lib/php/modules/ZendGuardLoader.so:  /usr/lib/php/modules/ZendGuardLoader.so: undefined symbol: zval_used_for_init
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/odbc.so' - /usr/lib/php/modules/odbc.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/pdo_odbc.so' - /usr/lib/php/modules/pdo_odbc.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/pdo_pgsql.so' - /usr/lib/php/modules/pdo_pgsql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/pdo_sqlite.so' - /usr/lib/php/modules/pdo_sqlite.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/pgsql.so' - /usr/lib/php/modules/pgsql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/modules/sqlite3.so' - /usr/lib/php/modules/sqlite3.so: cannot open shared object file: No such file or directory in Unknown on line 0
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for dompdf/dompdf v0.7.0 -> satisfiable by dompdf/dompdf[v0.7.0].
    - dompdf/dompdf v0.7.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
  Problem 2
    - dompdf/dompdf v0.7.0 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - yajra/laravel-datatables-oracle v6.18.0 requires dompdf/dompdf ^0.7 -> satisfiable by dompdf/dompdf[v0.7.0].
    - Installation request for yajra/laravel-datatables-oracle v6.18.0 -> satisfiable by yajra/laravel-datatables-oracle[v6.18.0].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php/php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
[marco@marco-note flarepoint]$ 
`

**Comment by Bottelet** [comment]
Hmmm, this seems very weird I will try and see if I can recreate the same error over the weekend. Haven't had any problems with composer install myself. and create-project shouldn't be necessary. Also can you tell me your composer version @cerelli

**Comment by cerelli** [comment]
Composer is 1.2.1
I try again and the error in the browser is:
`Not Found

The requested URL /flarepoint/public/login was not found on this server.`

**Comment by Bottelet** [comment]
So you got past the composer error, @cerelli? Did you rename the project? Else it should be Flarepoint-crm/public if you want to access it with another url, it should be as simple as renameing the folder. Or is it something else?

**Comment by cerelli** [comment]
The requested URL /Flarepoint-crm/public/login was not found on this server.

**Comment by Bottelet** [comment]
Hmm sounds like some apache problem, from what i can read. Have you changed any settings? and is it only with the crm or all sites?

**Comment by vignesh-subash** [comment]
App run perfectly on Windows machine but getting the  

> The requested URL /Flarepoint-crm/public/login was not found on this server.
error only on mac machine
