### ISSUE TITLE
Round 1: Suggestions

### ISSUE THREAD

**Issue by SuperlativeEntity** [Bottelet/Flarepoint-crm#3]
You can use custom middleware for these checks: $canCreateUser = Auth::user()->canDo('user.create');
Have a look at the repository pattern
Use pjax (loading views) and ajax (posts,gets etc.)
Use custom requests for validation (has an authorize method for canDo('user.create'); as well)
Store paths in a config file
You don't need to prefix foreign keys with fk, it's assumed to be a foreign key if it ends with _id.
Be careful with onDelete('cascade')
You can use faker to generate random data.
You don't need to repeat the same fields on both your create and edit views. It is possible to combine it into one. (Think maintainability: DRY)
Your display of errors is also repeated: @if($errors->any())

**Comment by Bottelet** [comment]
Thank you @SuperlativeEntity, I appreciate the feedback, and will definitely look into it.

**Comment by Bottelet** [comment]
@SuperlativeEntity 
I made use of : 

- Middlewares for checks
- Request for validation
- Also, I put my errors into the Master instead.

I am not sure what you mean by the following if you would bare to elaborate:

- PJax and Ajax, how would you do it differently than now? 
- Have a look at the repository pattern (It's on the to-do :))
- Store paths in a config file. Which paths are we exactly talking about here?
- I have tried to merge the forms for edit and create once, but was without luck, do you have any examples on this?

Thanks in advance
