### ISSUE TITLE
work number and personal number

### ISSUE THREAD

**Issue by sydwang** [Bottelet/Flarepoint-crm#30]
work number and personal number( user table) are both defined as integer, that would cause the numbers starting with 0 can't be stored as well as displayed correctly.
Defining them as string will be better, I think. 
Thank you.

**Comment by Bottelet** [comment]
Very good point @sydwang, i will definitely change this. Thanks for the suggestion.

**Comment by Bottelet** [comment]
https://github.com/Bottelet/Flarepoint-crm/commit/027ce6bc1d3402383b84172d8c1d4a30f6e1e007

Thank you again, I appreciate it... Also fixed it on clients, number, VAT, and zip code.
