### ISSUE TITLE
Modularization of features

### ISSUE THREAD

**Issue by vernard** [Bottelet/Flarepoint-crm#34]
Hi. I see a lot of potential with this project. I'm even considering using it as my own CRM.

With these potentials, it might become a bloated app in the future. Which is why I want to propose to add settings on what modules are enabled to make the app flexible to use for both corporate and small businesses.

For me, I don't need the "Departments" thing because I work alone. Let alone the "Office Meeting" feature that is planned for the future since I don't have a team to have an office meeting (client meeting would be nice tho).

Any plans going this "modular" path?

**Comment by Bottelet** [comment]
Hi @vernard 
I have been thinking about something like that, but I am not sure how to approach it 100%

But it's a good idea! and I will definitely consider it. If you have any good idea on how to approach it i am all ears!
