### ISSUE TITLE
Class 'App\Models\roleUser' not found

### ISSUE THREAD

**Issue by trixanapp** [Bottelet/Flarepoint-crm#36]
Insertion of dummy data
php artisan db:seed --class=UsersDummyTableSeeder (Creates 5 extra users and are required)
change: use App\Models\roleUser on use App\Models\RoleUser ...

**Comment by Bottelet** [comment]
I agree, Thanks

https://github.com/Bottelet/Flarepoint-crm/commit/91d69689f3cc55030c14c451ef4fcb8099e140a4
