### ISSUE TITLE
User tagging

### ISSUE THREAD

**Issue by FrankBloo** [Bottelet/Flarepoint-crm#37]
Hi,

First of all I would like to thank you for this project, it looks very promising. We are thinking about to use this in one of our student committee. Only we need to do a small adjustments to make sure the its matches our operations. 

I read the readme file and you mention the user tagging feature, i really like this feature. Do you by chance have any idea when you are going to implement this? It is alright if you dont know it yet. I'm just really curious :)

Thanks!

Frank

**Comment by Bottelet** [comment]
Hi Frank

Thank you.
I don't currently have any timeline on it, but it is one of the things I really want to be made, as I believe it improves the CRM significantly. So it is on the top of the list of to-do

**Comment by FrankBloo** [comment]
Okay, thank you for your quick answer. I understand its hard to have a timeline for it since it is complex to implement it.
