### ISSUE TITLE
Add buttons to delete files, see Client

### ISSUE THREAD

**Issue by mefist1990** [Bottelet/Flarepoint-crm#40]
Add buttons to delete files, see the Client, as not the file you want to delete is not possible to.

**Comment by mefist1990** [comment]
Added ability to delete documents from the clients
https://github.com/Bottelet/Flarepoint-crm/pull/42
![crm-del-doc](https://cloud.githubusercontent.com/assets/13015005/22013275/3d269598-dca9-11e6-8061-1ed349beaf52.png)

**Comment by mg-freelancer** [comment]
I will work for this feature :+1:

**Comment by Bottelet** [comment]
Thanks for the PR, it is merged.

**Comment by mefist1990** [comment]
Thank you for accepting my changes, I still have a number of ideas at the expense of your CRM, I will soon be added to your CRM additional functionality.

**Comment by mefist1990** [comment]
@Bottelet Thank you for accepting my changes, I still have a number of ideas at the expense of your CRM, I will soon be added to your CRM additional functionality.
