### ISSUE TITLE
Unable to create new table in the application.

### ISSUE THREAD

**Issue by vignesh-subash** [Bottelet/Flarepoint-crm#44]
Unable to create new table in the application. It shows error in vendor\laravel\Framework\src\Illuminate\Database\Migrations\Migrator.php on line 410

**Comment by vignesh-subash** [comment]
Unable to create new table in the application. It shows error in vendor\laravel\Framework\src\Illuminate\Database\Migrations\Migrator.php on line 410

**Comment by vignesh-subash** [comment]
i can able to create the table but unable to migrate the table values inside the table. when i run the 

> php artisan migrate:refresh --seed

it throw back the error 

> {ReflectionException] class DatabaseSeeder doesnot exist

**Comment by Bottelet** [comment]
Is this your own migration you have made? if then please share the code so i can help. If not, I have no problems seeding, but please share the steps you are taking

**Comment by Bottelet** [comment]
Also with I guess you figured out the variable thing? I don't recall having a variable named anything like that.

**Comment by vignesh-subash** [comment]
Yes im just tried with basic table implementation for adding salutation before name field the application. 
i have created the SalutationsTableSeed.php

`<?php
use Illuminate\Database\Seeder;
class IndustriesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        
        \DB::table('salutations')->delete();
        
        \DB::table('salutations')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'Mr.',
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Mrs.',
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'M/s.',
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Miss.',
            ),
        ));
    }
}`

after that i ran artisan command - php artisan make:migration create_salutations_table and php file getting created in the Database/Migration folder against the create_salutations_table. 
Following Issues are getting in
1- while doing this i can able to create the table in db.
2- Tables alone are getting created in the DB and Data fields are not getting created.
3- ReflectionExceptionError also getting, DatabaseSeeder not exist 
 
p.s i tried all the possible artisan commands but non of them are working for me

**Comment by Bottelet** [comment]
What you wanna do is run ```artisan make:migration create_salutations_table```, make your migration in the newly generated file. then in the your seed file, you wanna call it a correct name, a not on there already exsists, like ``ìndustriesTableSeeder```, then in the  ```Database/seeds/DatabaseSeeder.php``` you wanna insert ```$this->call('NameOfYourSeedFile');```

**Comment by vignesh-subash** [comment]
I tried what ever you mentioned above but still im getting the error.
