### ISSUE TITLE
Unable to add a task after installing the package

### ISSUE THREAD

**Issue by princelionelnzi** [Bottelet/Flarepoint-crm#45]
After installing `flarepoint-crm` and adding an user as admin, I try to add a task but i am getting the following error:

````
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`crm`.`tasks`, CONSTRAINT `tasks_client_id_foreign` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`))
````

**Comment by Bottelet** [comment]
Hmm i can only reproduce this error, if there are no clients to assign, i guess there need to be some validation there. Did you create a client @princelionelnzi?

**Comment by princelionelnzi** [comment]
No client has been created please.

**Comment by Bottelet** [comment]
Well a task needs to be assigned to a client, so create a new client under "New client" first, and all should work.
