### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by rlesouef** [Bottelet/Flarepoint-crm#47]
1. - git clone https://github.com/Bottelet/Flarepoint-crm.git
2. - table created
3. - .env modified
4. - composer install
i have the following error:

```
[RuntimeException]
  Could not scan for classes inside "tests/TestCase.php" which does not appear to be a file nor a folder
```

**Comment by Bottelet** [comment]
I haven't tested it, but this should fix it: 
https://github.com/Bottelet/Flarepoint-crm/commit/16ba1b5257990c579e70d49224fa6f510218e520

Thanks for posting the issue.
