### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by Bottelet** [Bottelet/Flarepoint-crm#5]
Write to a certain slack channel when for example.
- Lead is completed
- Task is completed
- New client is created

Give the user options in frontend to choose how slack should behave, whenever something happens.

**Comment by mg-freelancer** [comment]
Can I work on this feature ? if so please assign it to me

**Comment by Bottelet** [comment]
@mg-freelancer sure, go for it

**Comment by mg-freelancer** [comment]
So what are the slack channel info ? as url webhook , etc...

**Comment by Bottelet** [comment]
@mg-freelancer, It should be possible to use your own slack channel, so depending on the user they should be able to use their own slack channel, and not "mine". Make sense? So it should be possible to input their own url webhook etc.
