### ISSUE TITLE
\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 221 and defined

### ISSUE THREAD

**Issue by punit-gajjar** [Bottelet/Flarepoint-crm#55]
Hello , 

I have downloaded your code from https://github.com/Bottelet/Flarepoint-crm.git
->then i have created an empty database,
->renamed to .env.example to .env
->added my localhost configuration and changed the database name in .env
->then opened the command line and executed the command **composer install**
->then i had migrate all the tables using the command **php artisan migrate --seed**
->and at the end **php artisan key:generate** till now everything was going smooth, no errors anywhere 
but when i run the application  on **http://localhost/Flarepoint_crm/public/**

I got the below error.

> Parse error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in F:\wamp\www\punit\Flarepoint_crm\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php on line 477

Then i opened the above file and check the line 
and i found this
`function event(...$args)
 {
        return app('events')->dispatch(...$args);
 }`

Then i removed **...** and i refresh the page, that error was gone but i got the new error this time like below.

> Parse error: syntax error, unexpected '.' in F:\wamp\www\punit\Flarepoint_crm\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php on line 334

again i opened the above file and remove the **...** from the function wherever it was in the file.

then refreshed the page and again new Error.

This way i kept deleting the **...** from the class files and at the end i got the error 

> Argument 2 passed to Illuminate\View\Compilers\BladeCompiler::directive() must be callable, none given, called in F:\wamp\www\punit\Flarepoint_crm\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 221 and defined

**Comment by Bottelet** [comment]
Hmmm I'll have to test this out, you shouldn't have to delete any files for it to start working.

**Comment by Nesoi** [comment]
i think it not a specify code error,most of them are caused by environment configuration.
you should : 

- confirm .env params is right

```
DB_HOST=localhost
DB_DATABASE=your database name
DB_USERNAME=
DB_PASSWORD=
```

- try to start it using php-cli

u can go into the public directory then using 

```
php -S 0.0.0.0:81
```
see what happen

- make sure Storage directory can be written


- another way to start up

 u can just start this application with php artisan 


```
php artisan serve --port 8088
then visit it on http://localhost:8088
```

-check apache log
errors will be recorded in apache log.check it.


my english sucks,ive tried my best.sry for this..

**Comment by punit-gajjar** [comment]
@MaxMMX  , thanks for your quick response but would like to say my Credentials are correct in the .env file.  even Storage directory  is writable.

**Comment by Bottelet** [comment]
@punit-gajjar Did you fix this, or is still a problem for you?

**Comment by punit-gajjar** [comment]
@Bottelet, still have problem sir.
