### ISSUE TITLE
when i login, a warning was jumped out

### ISSUE THREAD

**Issue by railwayc** [Bottelet/Flarepoint-crm#62]
![tim 20170609091025](https://user-images.githubusercontent.com/8802233/26956923-f5a8d288-4cf3-11e7-904d-ee5cb3107bfb.png)

**Comment by Bottelet** [comment]
Is this when you login, or go to the leads page? Try and clear cache, does it still happen? I have had some problem with datatables, not being able to get to complete the ajax call.

**Comment by Bottelet** [comment]
Can't debug without any more information
