### ISSUE TITLE
composer install fails due to dependencies

### ISSUE THREAD

**Issue by faphdev** [Bottelet/Flarepoint-crm#63]
Hello,

Can you please provide some more instructions how to install the project?
I followed your instructions but the composer install command fails with about 39 problems.
It looks like the php version does not satisfy the version required. I did not install php beforehand and I am not able to yum update php...
----------------------------------------------------------------------------------------------------
composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
--------------------------------------------------------------------------------------------------

**Comment by Bottelet** [comment]
Hmm, it sounds like you have to update your PHP version on you computer, which is something you have to Google yourself too, depending on what system you are using.

**Comment by faphdev** [comment]
OK thank you.
In your instructions you say:
- Create an empty database table
- Copy the .env.example to .env and insert the Database config
What is the name of the table/s to be created? What is expected (to be added) in the .env file for the app to work?
Thanks!

**Comment by Bottelet** [comment]
@faphdev Have you worked with Laravel before? Check the database/migrations folder, there are all the tables that will be created, in the .env file, there is expected to put your database credentials.
