### ISSUE TITLE
add task error

### ISSUE THREAD

**Issue by zf2** [Bottelet/Flarepoint-crm#64]
I encountered a mistake when creating a task, if I did not create a client first.
![qq 20170629174221](https://user-images.githubusercontent.com/11845198/27681607-6945c59e-5cf2-11e7-9cbc-909556491b46.png)

**Comment by Bottelet** [comment]
@zf2 A task needs to have a client, a task can not be assigned to nothing.

**Comment by Bottelet** [comment]
Should probably have some sort of error handling instead of thorwing an exception

**Comment by zf2** [comment]
yeah，you are right. My current solution is modified it.
![qq 20170630181044](https://user-images.githubusercontent.com/11845198/27731379-53239606-5dbf-11e7-83dc-51cbe23f2a84.png)

**Comment by Bottelet** [comment]
@zf2 I've added it to the validatio rules in this commit:
https://github.com/Bottelet/Flarepoint-crm/commit/8c7f705530604311e27f5a7c16abf287d11857f9

Thanks for the heads up
