### ISSUE TITLE
Demo doesn't working

### ISSUE THREAD

**Issue by karamucho** [Bottelet/Flarepoint-crm#69]
Hi,
Demo site ec2-34-248-108-133.eu-west-1.compute.amazonaws.com  doesn't work, is there a chance to bring any demo to live?

Cheers,
karamucho

**Comment by Bottelet** [comment]
Hello @karamuch, I'm currently running the ticket-conductor.com demo, and will not be running both at the same time, as it costs money to run them, it might come online at some point but not right now
