### ISSUE TITLE
Code error of "This cache store does not support tagging "

### ISSUE THREAD

**Issue by asterixphp** [Bottelet/Flarepoint-crm#70]
Hello Bottelet
I find the your code in github and try the install my xampp server in windows10.
But I can't install the your code.
First login window is shown.
But after login by the user:: "admin@admin.com" pass:: "admin123" , I see the 3 ErrorException.
1.This cache store does not support tagging. (View: D:\xampp\htdocs\Flarepoint-crm-develop\resources\views\layouts\master.blade.php) (View: D:\xampp\htdocs\Flarepoint-crm-develop\resources\views\layouts\master.blade.php)
2.This cache store does not support tagging. (View: D:\xampp\htdocs\Flarepoint-crm-develop\resources\views\layouts\master.blade.php)
3.This cache store does not support tagging.
Why this event occur?
How to see the your dashboard part?
my php version is the 5.6.14 and way(composer install  --no-dev) use
Do you help me?

**Comment by Bottelet** [comment]
Hmm I haven't experienced this before @asterixphp, can you try and change the config/cache from 
`'default' => env('CACHE_DRIVER', 'array'),` to `'default' => env('CACHE_DRIVER', 'memcached'),`

**Comment by asterixphp** [comment]
Hello
The error is the common error in Laravel framework.
I find the similar issues "https://github.com/Zizaco/entrust/issues/468"
But it isn't work.
same error.

**Comment by asterixphp** [comment]
Already I solved the problem .
In .env file change to "CACHE_DRIVER=array" from "CACHE_DRIVER=file".
Thanks for your help

**Comment by msankar1991** [comment]
Still its not working. Getting same above error always find .env file config also

`APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:A4iGUSFfS08b7QY65t0tmjcyijRGdrISzqz1kuivxEo=
APP_DEBUG=true

DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=flarepoint_crm
DB_USERNAME=root
DB_PASSWORD=

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null`
