### ISSUE TITLE
Demo site seems to be down

### ISSUE THREAD

**Issue by Ali-Al1** [Bottelet/Flarepoint-crm#71]
![image](https://user-images.githubusercontent.com/11404482/29923150-58c37632-8e50-11e7-9735-4caa14df3964.png)

**Comment by Bottelet** [comment]
Hello @Ali-Al1  I know I am currently hosting https://github.com/Bottelet/ticket-conductor, instead, as it costs money I'm not gonna hosts all the demos at once.
