### ISSUE TITLE
Clients assigned did not work correctly

### ISSUE THREAD

**Issue by nguyencuonghut** [Bottelet/Flarepoint-crm#72]
Hi @Bottelet,
When I tried to run Flarepoint-crm on my local PC, the function to display the clients of each user did not work correctly.
The error as below:
![image](https://user-images.githubusercontent.com/26396504/30174136-3c48688a-9424-11e7-9b8f-f57cccaf71f3.png)
Can you check it?

**Comment by Bottelet** [comment]
Hmm I'll have to see if I can look into it over the weekend, and reproduce the problem.

**Comment by nguyencuonghut** [comment]
May be the problem  is in:
ajax: '{!! route('users.clientdata', ['id' => $user->id]) !!}'
When I try to replace route by url, the error is not occurred anymore.

**Comment by Bottelet** [comment]
Fixed here:
5d0ee8a8d20920ad1370bfde29fb4db166edfa9f

Thanks for reporting the bug
