### ISSUE TITLE
Error running migrations on [Docker]

### ISSUE THREAD

**Issue by ingedman** [Bottelet/Flarepoint-crm#73]
Hi @Bottelet 

Not sure what is the reason, I just download the Docker containers and got this error.

`root@88e0545fb571:/var/www/html# php artisan migrate --seed

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Parse error: syntax error, unexpected '20161104200855' (T_LNUMBER), expecting identifier (T_STRING)

root@88e0545fb571:/var/www/html#`

Thanks

**Comment by Bottelet** [comment]
I have to be honest I'm not the strongest in Docker @saleh199 Made the docker image, maybe if we are lucky we can summon him, else I might try and debug on it over the weekend, and see if I can reproduce it. Thanks
