### ISSUE TITLE
Error when display the "Created at" on leadtab.blade.php

### ISSUE THREAD

**Issue by nguyencuonghut** [Bottelet/Flarepoint-crm#75]
This line is not correct:
`<td>{{date('d, M Y, H:i', strTotime($lead->cotact_date))}}  </td>`

It should be:
`<td>{{date('d, M Y, H:i', strTotime($lead->contact_date))}}  </td>`

**Comment by Bottelet** [comment]
Fixed here:
5d0ee8a8d20920ad1370bfde29fb4db166edfa9f

Thanks for reporting the bug
