### ISSUE TITLE
Error display Deadline of Task

### ISSUE THREAD

**Issue by nguyencuonghut** [Bottelet/Flarepoint-crm#76]
In TasksController:
`            ->editColumn('deadline', function ($tasks) {
                return $tasks->created_at ? with(new Carbon($tasks->created_at))
                    ->format('d/m/Y') : '';
            })`
should be:
`            ->editColumn('deadline', function ($tasks) {
                return $tasks->deadline? with(new Carbon($tasks->deadline))
                    ->format('d/m/Y') : '';
            })`
And the same in function taskData() of UsersController.

**Comment by Bottelet** [comment]
@nguyencuonghut Why don't you open a PR? :) I'll might fix it later, if there is no PR, with the things you have commented on.

**Comment by Bottelet** [comment]
Fixed here:
5d0ee8a8d20920ad1370bfde29fb4db166edfa9f

Thanks for reporting the bug
