### ISSUE TITLE
Error display contact_date of Lead

### ISSUE THREAD

**Issue by nguyencuonghut** [Bottelet/Flarepoint-crm#77]
In function leadData of UsersController:
`            ->editColumn('contact_date', function ($leads) {
                return $leads->created_at ? with(new Carbon($leads->created_at))
                    ->format('d/m/Y') : '';
            })`

should be:
`            ->editColumn('contact_date', function ($leads) {
                return $leads->contact_date? with(new Carbon($leads->contact_date))
                    ->format('d/m/Y') : '';
            })`

**Comment by Bottelet** [comment]
Fixed here:
5d0ee8a8d20920ad1370bfde29fb4db166edfa9f

Thanks for reporting the bug
