### ISSUE TITLE
Installation Guidelines

### ISSUE THREAD

**Issue by sethokayba** [Bottelet/Flarepoint-crm#78]
Hello,

Can you explain the installation process in more details.

For installation with a MySQL server running on localhost : 3306 , how to do it ?

thanks in advance.
Cheers.

**Comment by Bottelet** [comment]
Seems like you need to google how to setup a mySQL databse locally.

**Comment by sethokayba** [comment]
Seems that you did not understand my question.
Thanks anyway.

**Comment by Bottelet** [comment]
Sorry let me repgrase, seems like you need to google, how to setup a laravel project :)

**Comment by sethokayba** [comment]
i'll accept this :)
thank you and keep the googd work.
