### ISSUE TITLE
Composer Install gives error

### ISSUE THREAD

**Issue by rahul7777yadav** [Bottelet/Flarepoint-crm#79]
Hi I am using php version 7.0.1 but still getting this error :

> Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  

> Problem 1
>     - Installation request for phpunit/php-token-stream 2.0.0 -> satisfiable by
> phpunit/php-token-stream[2.0.0].
>     - phpunit/php-token-stream 2.0.0 requires php ^7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
>   Problem 2
>     - phpunit/php-token-stream 2.0.0 requires php ^7.0 -> your PHP version (5.6.25) does not satisfy that requirement.
>     - phpunit/php-code-coverage 4.0.8 requires phpunit/php-token-stream ^1.4.2 || ^2.0 -> satisfiable by phpunit/php-token-stream[2.0.0].
>     - Installation request for phpunit/php-code-coverage 4.0.8 -> satisfiable by phpunit/php-code-coverage[4.0.8]. @Bottelet

**Comment by Bottelet** [comment]
Hmm seems weird @rahul7777yadav Can you try and do a php -v and be sure it's 7.0.1, or maybe you have some old php versions lying as well, there might confuse it?

**Comment by rahul7777yadav** [comment]
Actually i had to change my Environment variable path to solve this .

Thanks for reply :)
