### ISSUE TITLE
Feature search is case sensitive

### ISSUE THREAD

**Issue by sydwang** [Bottelet/Flarepoint-crm#80]
Flarepoint is a very good product and I have installed and tested at least two of your release versions.
Found that the function search is case sensitive. 
If it's not, this feature could be more powerful and reasonable.
Good day.

Sydwang

**Comment by Bottelet** [comment]
Not sure what search we are talkign about here @sydwang

**Comment by sydwang** [comment]
I created a lead which has a word EOI in its title, but it couldn't be found by searching eoi.  In order to let it appear in search result list, I have to search the word EOI.
Have I addressed the issue clearly?
Thank you.

Charles

**Comment by Bottelet** [comment]
I see, it's the search function on leads, tasks etc we are talking about correct?

**Comment by sydwang** [comment]
Hi, all
Exactly.
If it is not case sensitive, it would be more powerful in terms of feature.
Thank you.

Charles

**Comment by jhuebel** [comment]
Updated DataTables resolves this issue.
