### ISSUE TITLE
DataTables warning: table id=clients-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

### ISSUE THREAD

**Issue by alexandervargas** [Bottelet/Flarepoint-crm#84]
![image](https://user-images.githubusercontent.com/19354310/35426646-8a05bc04-0232-11e8-8785-8a7cec4e2b0a.png)
DataTables warning: table id=clients-table - Ajax error. For more information about this error, please see http://datatables.net/tn/7

**Comment by Bottelet** [comment]
@alexandervargas Still having this problem, or did you figure it out?

**Comment by Bottelet** [comment]
No response closing issue
