### ISSUE TITLE
Out of memory using big client table

### ISSUE THREAD

**Issue by marctonon** [Bottelet/Flarepoint-crm#87]
Dear friend, I am using this excelent app and I've tried to manage 300k clients. During the first 'php artisan serve', I've got the error 'Allowed memory size of 536870912 bytes exhausted in Laravel
'. 

File: ClientRepository.php

Please, kindly change the code 

    public function getAllClientsCount()
    {
        return Client::all()->count();
    }

to 

    public function getAllClientsCount()
    {
        return Client::count();
    }

otherwise the memory will be totally used till end. 

P.S.: I don't know how to send a pull request.

**Comment by Bottelet** [comment]
Solved by yourself here :)
https://github.com/Bottelet/Flarepoint-crm/pull/88/commits/566277e0b5a60c913f82b4bf3a4c05a1e07d40eb

Closing the issue.
