### ISSUE TITLE
How to install on mac?

### ISSUE THREAD

**Issue by prasadh13** [Bottelet/Flarepoint-crm#89]
Please let me know how to install this crm on mac. The installation steps from the wiki do not work for mac. I have the git repo and composer on mac. I am on PHP v5.6.30 which came default with mac. I am stuck at the following error- 

`Fatal error: require(): Failed opening required '/Users/prasad/Desktop/crm/Flarepoint-crm/bootstrap/../vendor/autoload.php' (include_path='.:') in /Users/prasad/Desktop/crm/Flarepoint-crm/bootstrap/autoload.php on line 17`

Any help will be appreciated. TIA!

**Comment by Bottelet** [comment]
Hello @prasadh13 Have you tried to do `Composer install`?
