### ISSUE TITLE
Excel Import/export

### ISSUE THREAD

**Issue by Bottelet** [Bottelet/Flarepoint-crm#9]
Export users, clients, tasks, and leads as XML or CSV, And be able to upload clients etc, from other XML/CSV files to Flarepoint

**Comment by EDDYMENS** [comment]
Also, I am looking at the import and export issue. How should it be? A whole new tab were all imports & exports happen?

**Comment by Bottelet** [comment]
I'm thinking on the clients, tasks index page etc. that there should be an import/export button where you can upload the XML/CSV etc to the database

**Comment by EDDYMENS** [comment]
Ah got it. Either ways works . It's why I wanted to know if you had a preference.
