### ISSUE TITLE
After having installed, it does not load the views

### ISSUE THREAD

**Issue by joreluix** [Bottelet/Flarepoint-crm#90]
![screenshot-2018-5-7 index of flarepoint-crm 1](https://user-images.githubusercontent.com/32938445/39714294-35f8df12-51ef-11e8-8cb8-949b3a624b07.png)

**Comment by Bottelet** [comment]
Seems mostly something is wrong with your web server, nginx or apache? you have to make sure it looks at /public as the root folder.

**Comment by joreluix** [comment]
Its apache. Thanks for the info, i solved it, add a .htaccess file into main folder with next code:

RewriteEngine On
RewriteCond %{HTTP_HOST} ^localhost$
RewriteRule (.*)$ http://localhost/"my-folder"/public [R=301,L]
