### ISSUE TITLE
Db Connection Error during Installing

### ISSUE THREAD

**Issue by successus** [Bottelet/Flarepoint-crm#91]
I have done all 3 steps for installing. I use docker, but during login, i get an error: 
I think that the trouble is with db connection. could you help?  
How can I connect to the db, when I use docker?

QueryException
SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client (SQL: select * from `users` where `email` = admin@admin.com limit 1)

PDOException
PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password]

**Comment by Bottelet** [comment]
I am sorry, my docker knowledge is not very strong, someone else created the docker image.
