### ISSUE TITLE
shouldn't the user have access to see his tasks only?

### ISSUE THREAD

**Issue by centrust** [Bottelet/Flarepoint-crm#97]
Hi
This looks like what I was looking for,
But 
shouldn't the user have access to see his tasks only?

**Comment by Thirdy-jea** [comment]
Same observation. Any fix on this sir Bottelet?

**Comment by Bottelet** [comment]
No, that was not the intention but could be an option. I don't see why the rest of the company should not be able to see what each user is working on.

**Comment by jhuebel** [comment]
I will be adding this feature at some point to my fork and will submit a PR when it's ready.

The following "view" role permissions will be added:

- View All Clients
- View All Contacts
- View All Tasks
- View All Invoices
- View All Leads

In additional, new "My" views will be added that only show the clients, contacts, etc that are assigned to you. There will also be role permissions for assigning clients, tasks and leads to other users.

No concrete timeframe on when I'll be adding this, but it should be in the next few weeks.

**Comment by SkowronekArt** [comment]
> * View All Invoices

-> I will be very thankfull when you do this :) Thanks in advance!

**Comment by jhuebel** [comment]
So you know, PR #113 doesn't prevent the user from seeing all of the clients, contacts, tasks and leads. It just adds views called "My Clients", "My Contacts", etc that filter the lists. But at the moment, users can still look at "All Clients", "All Contacts", etc. I haven't added the role permissions yet.

**Comment by jhuebel** [comment]
1.3 adds this feature, without access controls. Closing since access control improvements are on the roadmap for a future version.
