### ISSUE TITLE
translation to Spanish

### ISSUE THREAD

**Issue by alek10c** [Bottelet/Flarepoint-crm#98]
Hola, me gustaría colaborar en el proyecto, en este momento estoy traduciendo al español.

`{
  "Name": "Nombre",
  "name": "nombre",
  "Company": "Compañia",
  "company": "compañia",
  "Mail": "Mail",
  "mail": "mail",
  "Number": "Número",
  "number": "numere",
  "Create New Client": "Crear Nuevo Cliente",
  "Update client": "Actualizar cliente",
  "Tasks": "Tareas",
  "Leads": "Registros",
  "Documents": "Documentos",
  "Invoices": "Facturas",
  "Assign new user": "Asignar nuevo usuario",
  "Primary number": "Número Principal",
  "Secondary number": "Número Alternativo",
  "vat": "vat",
  "Vat": "Vat",
  "Industry": "Industria",
  "Company type": "tipo de compañía",
  "File": "Archivo",
  "Size": "tamaño",
  "Max size": "Maximo tamaño",
  "Created at": "Creado el",
  "All Documents": "Todos los documentos",
  "ID": "ID",
  "Hours": "Houras",
  "Totalt amount": "Cantidad total",
  "Invoice sent": "Factura Enviada",
  "Payment received": "Pago recibido",
  "Title": "Titulo",
  "Assigned user": "Usuario asignado",
  "Deadline": "Fecha tope",
  "New Lead": "Nuevo Registro",
  "All Leads": "Todos Registros",
  "All Tasks": "Todas las Tareas",
  "New Tsask": "Nuevo Tarea",
  "Description": "Descripción",
  "Create Department": "Crear departamento",
  "Action": "Acción",
  "Delete": "Eliminar",
  "Api key": "Api key",
  "Organization id": "Organización",
  "Update": "Actualizar",
  "Integrations": "Integraciones",
  "Dashboard": "Tablero",
  "Profile": "Perfil",
  "Clients": "Clientes",
  "All Clients": "Todos Los Clientes",
  "New Client": "Nuevo Cliente",
  "Users": "Usuarios",
  "All Users": "Todos Los Usuarios",
  "New User": "Nuevo Usuario",
  "Departments": "Departamentos",
  "All Departments": "Todos Los Departamentos",
  "New Department": "Nuevo Departamento",
  "Settings": "Ajustes",
  "Overall Settings": "Ajustes generales",
  "Role Management": "Gestión de roles",
  "Integrations": "Integraciones",
  "Sign Out": "Desconectar",
  "Note": "Nota",
  "Status": "Estado",
  "Time": "Hora",
  "Assign user": "Asignar usuario",
  "Assign Client": "Asignar cliente",
  "Create new Lead": "Crear nuevo Registro",
  "Assigned": "Asignado",
  "Lead Information": "Información de registro",
  "Assigned to": "Asignado a",
  "Follow up": "Seguir",
  "Tasks completed this month": "Tareas completadas este mes",
  "Leads completed this month": "Registros completados este mes",
  "Total hours registered": "Total de horas registradas",
  "More info": "Más información",
  "Comment by": "Comentario por",
  "Modified": "Modificado",
  "Add Comment": "Agregar comentario",
  "Add Note": "Añadir la nota",
  "Tasks created today": "Tareas creadas hoy",
  "Tasks completed today": "Tareas completadas hoy",
  "Leads created today": "Registros creadas hoy",
  "Leads completed today": "Registros completados hoy",
  "Users": "Usuarios",
  "Completed": "Completado",
  "Tasks each month": "Tareas cada mes",
  "Leads each month": "Registros cada mes",
  "Add new Role": "Añadir nuevo Rol",
  "All Roles": "Todos Roles",
  "Save Role": "Guardar Rol",
  "If Allowed only user who are assigned the task & the admin can complete the task.": "Si se permite, solo los usuarios que tienen asignada la tarea y el administrador pueden completar la tarea.",
  "If Not allowed anyone, can complete all tasks.": "Si no está permitido a nadie, puede completar todas las tareas.",
  "If Allowed only user who are assigned the task &amp; the admin can assign another user.": "Si se permite, solo los usuarios que tienen asignada la tarea &amp; El administrador puede asignar otro usuario.",
  "If Not allowed anyone, can assign another user.": "Si no se permite a nadie, se puede asignar otro usuario.",
  "Task completion": "Tarea completadas",
  "Task assigning": "Tarea Asignada",
  "Lead completion": "Registro Completado",
  "Lead assigning": "Registro Asignado",
  "Allowed": "Permitido",
  "Not allowed": "No Permitido",
  "If Allowed only user who are assigned the lead & the admin can complete the lead.": "Si se permite, solo los usuarios que tienen asignado el cliente potencial y el administrador pueden completar el cliente potencial.",
  "If Not allowed anyone, can complete all leads.": "Si no se permite a nadie, puede completar todos Registros.",
  "If Allowed only user who are assigned the lead &amp; the admin can assign another user.": "Si se permite, solo los usuarios que tienen asignado el encabezado &amp; El administrador puede asignar otro usuario.",
  "If Not allowed anyone, can assign another user.": "Si no se permite a nadie, se puede asignar otro usuario.",
  "Save overall settings": "Guardar la configuración general",
  "Create task": "Crear Tarea",
  "Create user": "Crear Usuario",
  "Update user": "Actualizar Usuario",
  "Assign role": "Asignar rol",
  "Assign department": "Asignar departamento",
  "Passowrd": "Contraseña",
  "Confirm password": "Confirmar Contraseña",
  "Personal number": "Número personal",
  "Work number": "Número de trabajo",
  "Email": "Email",
  "Address": "Dirección",
  "Image": "Imagen",
  "Open": "Abierto",
  "Closed": "Cerrado",
  "Close": "Cerrar",
  "Task information": "Información de la tarea",
  "Add time": "Agregar Hora",
  "Hourly price": "Precio por hora",
  "Time spend": "Tiempo gastado",
  "Register time": "Hora de registro",
  "Send mail with invoice to Customer?(Cheked = Yes):": "¿Enviar correo con factura al cliente?(Cheked = Yes):",
  "Client": "Cliente",
  "Contact":"Contrato",
  "Completed": "Completado",
  "Not interested": "No Interesado",
  "Complete Lead": "Registro Completado",
  "Next follow up": "Siguiente seguimiento",
  "Change deadline": "Cambiar plazo",
  "Update follow up": "Actualizar seguimiento",
  "Tasks assigned": "Tareas asignadas",
  "Create user": "Crear usuario",
  "Edit user": "Editar usuario",
  "All users": "Todos los Usuarios",
  "Close task": "Cerrar Tarea",
  "Time management": "Gestión del tiempo",
  "Create invoice": "Crear factura",
  "Create": "Crear",
  "Clients assigned": "Clientes asignados",
  "Order summary": "Resumen de la orden",
  "Item name": "Nombre del árticulo",
  "Item price": "Precio del articulo",
  "Hours used": "Horas utilizadas",
  "Total": "Total",
  "Insert new item": "Insertar nuevo elemento",
  "Payment Received": "Pago recibido",
  "Invoice sent": "Factura Enviada",
  "Leads assigned": "Registros asignados",
  "Invoice paid date": "Fecha de pago de la factura",
  "Time Managment For This Invoice": "Gestión del tiempo para esta facturae",
  "Time spend (Hours)": "Tiempo gastado (Houras)",
  "Hourly price": "Precio por hora",
  "Register time": "Hora de registro",
  "Yes": "Si",
  "No": "No",
  "Create lead": "Crear Registro",
  "Insert task title (will be shown on invoice": "Insertar título de la tarea (se mostrará en la factura)",
  "A short description, as to what is being billed": "Una breve descripción de lo que se está facturando.",
  "Can't insert new invoice line, to already sent invoice": "No se puede insertar una nueva línea de factura, a la factura ya enviada",
  "Once a invoice has been send, no new invoice lines can be added": "Una vez que se ha enviado una factura, no se pueden agregar nuevas líneas de factura",
  "We have found this contact from your, billing integration, do you wish for us to send it to your billing system aswell?": "Hemos encontrado este contacto de su integración de facturación. ¿Desea que lo enviemos también a su sistema de facturación?",
  "Users All": "Todos los Usuarios",
  "New Task": "Nueva Tarea"
}
`

**Comment by Bottelet** [comment]
Hi @alek10c, Could you open a Pull request instead?

**Comment by alek10c** [comment]
success

**Comment by Bottelet** [comment]
Thanks. Fixed in ed64082
