### ISSUE TITLE
Error in counting the leads created today

### ISSUE THREAD

**Issue by alek10c** [Bottelet/Flarepoint-crm#99]
I leave the code to correct

app\Http\Controllers\PagesController.php

original
`        $completedLeadsToday = $this->leads->completedLeadsToday();
        $createdLeadsToday = $this->leads->completedLeadsToday();
`
corrected
`
$completedLeadsToday = $this->leads->completedLeadsToday();
        $createdLeadsToday = $this->leads->createdLeadsToday();
`

**Comment by Bottelet** [comment]
Hi @alek10c, Could you open a Pull request instead?

**Comment by alek10c** [comment]
success

**Comment by Bottelet** [comment]
Thanks. Fixed in ed64082
